name = "allbot"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "allbot-db"
database_id = "cbf15283-7326-4b7f-89a1-908e30e2aa66"
